language: node_js
os:
  - osx
node_js:
  - "4"
  - "6"
script:
  - id
  - id nobody
  - touch A
  - sudo chown nobody A
  - node -p 'fs.statSync("A")'
  - node -p 'x = fs.statSync("A"); fs.chownSync("A", x.uid, x.gid)'
